name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction --prefer-dist

    - name: Set up environment variables
      run: |
        echo "APP_ENV=testing" >> .env

    # Commenté pour sauter l'exécution des tests
    # - name: Run tests
    #   run: |
    #     ./vendor/bin/phpunit --configuration phpunit.xml

    - name: Skip tests (or add any other step here)
      run: echo "Tests are skipped."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()  # Cette ligne indique que le déploiement se fait uniquement si le job "build" est un succès

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        echo "Deploying application"
        # Ajoutez ici vos commandes de déploiement (par exemple via SSH, FTP, ou un autre outil)
